sudo: required
services:
 - docker
 
before_install:
 - docker build -t iamsanthosh/docker-springboot-rest -f Dockerfile.dev .
 
script:
 - docker run iamsanthosh/docker-springboot-rest npm test -- --coverage

 