# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine
WORKDIR '/app'
ARG JAR_FILE=docker-springboot-rest-0.0.1-SNAPSHOT.jar	
ADD ${JAR_FILE} docker-springboot-rest.jar
COPY ${JAR_FILE} docker-springboot-rest.jar
ENTRYPOINT ["java","-jar","/docker-springboot-rest.jar"]
